"""
Untapped Demand Service
───────────────────────
Identify hex cells with HIGH DEMAND signal but LOW SUPPLY (no nearby store).
This is the actual answer to "where should we expand?"

Demand signal = population × income × amenity richness
Supply signal = inverse distance to nearest existing store

Untapped score = normalized_demand × (1 - normalized_supply)

Output is a hex layer the UI renders alongside the performance heatmap.
"""
from typing import Any, Dict, List, Optional, Tuple

import math
import h3

from app.utils import get_logger, safe_float

log = get_logger("services.untapped_demand")

# ── Tunables ────────────────────────────────────────────────────────────────
DEFAULT_RESOLUTION = 6        # district-ish hexes work well for "where to go"
DEFAULT_SUPPLY_RADIUS_KM = 3  # store within this distance = covered
MIN_DEMAND_PERCENTILE = 50    # only return hexes above median demand
MAX_RESULTS = 200             # cap output for UI performance


def _haversine_km(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lng2 - lng1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def compute_untapped_demand(
    candidate_hexes: List[Dict[str, Any]],
    existing_stores: List[Dict[str, Any]],
    resolution: int = DEFAULT_RESOLUTION,
    supply_radius_km: float = DEFAULT_SUPPLY_RADIUS_KM,
    min_demand_percentile: int = MIN_DEMAND_PERCENTILE,
) -> Dict[str, Any]:
    """
    candidate_hexes: list of {cell, lat, lng, population, income_index, amenity_count}
                     — typically generated by sampling the tenant's territory
                       via a hex grid and enriching with demographics.
    existing_stores: list of {lat, lng} dicts (the tenant's own stores)

    Returns
    -------
    {
        "hexes": [
            {
                "cell":              "8a5e8d3c...",
                "boundary":          [[lat, lng], ...],
                "center":            [lat, lng],
                "demand_score":      0.85,    # 0-1 normalised
                "supply_score":      0.20,    # 0-1 normalised (1 = saturated)
                "untapped_score":    0.68,    # 0-1
                "population":        45_000,
                "income_index":      0.62,
                "nearest_store_km":  4.7,
                "classification":    "high" | "medium" | "low",
            }, ...
        ],
        "resolution":      int,
        "total_cells":     int,
        "supply_radius_km": float,
    }
    """
    if not candidate_hexes:
        return {
            "hexes": [],
            "resolution": resolution,
            "total_cells": 0,
            "supply_radius_km": supply_radius_km,
        }

    # ── 1. Demand score: weighted product of pop × income × amenities ──
    pops = [safe_float(c.get("population", 0)) for c in candidate_hexes]
    incomes = [safe_float(c.get("income_index", 0)) for c in candidate_hexes]
    amenities = [safe_float(c.get("amenity_count", 0)) for c in candidate_hexes]

    def normalise(values: List[float]) -> List[float]:
        if not values:
            return []
        vmax = max(values) or 1.0
        return [v / vmax for v in values]

    pops_n = normalise(pops)
    incomes_n = normalise(incomes)
    amenities_n = normalise(amenities)

    demand_scores = []
    for i in range(len(candidate_hexes)):
        # Weighted geometric-ish blend: population dominates, income amplifies,
        # amenities indicate destination/dwell-time activity
        d = (
            0.50 * pops_n[i] +
            0.30 * incomes_n[i] +
            0.20 * amenities_n[i]
        )
        demand_scores.append(d)

    # ── 2. Supply score: inverse distance to nearest store ──
    supply_scores = []
    nearest_distances = []
    for c in candidate_hexes:
        clat, clng = c.get("lat"), c.get("lng")
        if clat is None or clng is None:
            supply_scores.append(1.0)
            nearest_distances.append(0.0)
            continue
        if not existing_stores:
            supply_scores.append(0.0)
            nearest_distances.append(float("inf"))
            continue

        # Find nearest store
        nearest = min(
            _haversine_km(clat, clng, safe_float(s.get("lat")), safe_float(s.get("lng")))
            for s in existing_stores
        )
        nearest_distances.append(nearest)
        # Within supply_radius_km = considered "covered" (supply = 1)
        # Beyond 3x that = uncovered (supply = 0)
        if nearest <= supply_radius_km:
            supply = 1.0
        elif nearest >= supply_radius_km * 3:
            supply = 0.0
        else:
            # Linear ramp between
            supply = 1.0 - ((nearest - supply_radius_km) / (supply_radius_km * 2))
        supply_scores.append(supply)

    # ── 3. Untapped = demand × (1 − supply) ──
    untapped_scores = [
        demand_scores[i] * (1.0 - supply_scores[i])
        for i in range(len(candidate_hexes))
    ]

    # ── 4. Filter to above-median-demand hexes (so we don't return empty rural cells) ──
    if demand_scores:
        sorted_demand = sorted(demand_scores)
        cutoff_idx = int(len(sorted_demand) * min_demand_percentile / 100)
        demand_cutoff = sorted_demand[min(cutoff_idx, len(sorted_demand) - 1)]
    else:
        demand_cutoff = 0.0

    # ── 5. Build output ──
    hexes_out: List[Dict[str, Any]] = []
    for i, c in enumerate(candidate_hexes):
        if demand_scores[i] < demand_cutoff:
            continue

        cell = c.get("cell")
        # Recompute boundary from cell if needed
        boundary = c.get("boundary")
        if not boundary and cell:
            try:
                boundary = [[float(la), float(ln)] for la, ln in h3.cell_to_boundary(cell)]
            except Exception:
                boundary = None

        u = untapped_scores[i]
        if u >= 0.6:
            cls = "high"
        elif u >= 0.3:
            cls = "medium"
        else:
            cls = "low"

        hexes_out.append({
            "cell":             cell,
            "boundary":         boundary,
            "center":           [c.get("lat"), c.get("lng")],
            "demand_score":     round(demand_scores[i], 3),
            "supply_score":     round(supply_scores[i], 3),
            "untapped_score":   round(u, 3),
            "population":       int(safe_float(c.get("population", 0))),
            "income_index":     round(safe_float(c.get("income_index", 0)), 3),
            "amenity_count":    int(safe_float(c.get("amenity_count", 0))),
            "nearest_store_km": round(nearest_distances[i], 2) if nearest_distances[i] != float("inf") else None,
            "classification":   cls,
        })

    # Sort by untapped score, descending; cap result count
    hexes_out.sort(key=lambda h: -h["untapped_score"])
    hexes_out = hexes_out[:MAX_RESULTS]

    log.info(
        "untapped_demand: %d candidates → %d cells (resolution=%d, radius=%.1fkm)",
        len(candidate_hexes), len(hexes_out), resolution, supply_radius_km,
    )

    return {
        "hexes":           hexes_out,
        "resolution":      resolution,
        "total_cells":     len(hexes_out),
        "supply_radius_km": supply_radius_km,
    }


def generate_candidate_grid(
    bounds: Tuple[float, float, float, float],
    resolution: int = DEFAULT_RESOLUTION,
) -> List[Dict[str, Any]]:
    """
    Generate a hex grid covering the given bounding box.
    Returns a list of {cell, lat, lng, boundary} dicts — caller is expected
    to enrich with demographics and POI counts before passing to
    compute_untapped_demand().

    bounds: (lat_min, lat_max, lng_min, lng_max)
    """
    lat_min, lat_max, lng_min, lng_max = bounds

    # Sample lat/lng grid at appropriate density for the resolution
    # Approximate cell edge length in degrees by resolution
    cell_edge_deg = {
        4: 0.6, 5: 0.22, 6: 0.08, 7: 0.03, 8: 0.011, 9: 0.004,
    }.get(resolution, 0.08)

    seen_cells: set = set()
    out: List[Dict[str, Any]] = []

    lat = lat_min
    while lat <= lat_max:
        lng = lng_min
        while lng <= lng_max:
            try:
                cell = h3.latlng_to_cell(lat, lng, resolution)
            except Exception:
                lng += cell_edge_deg
                continue
            if cell not in seen_cells:
                seen_cells.add(cell)
                clat, clng = h3.cell_to_latlng(cell)
                boundary = [[float(la), float(ln)] for la, ln in h3.cell_to_boundary(cell)]
                out.append({
                    "cell": cell,
                    "lat": float(clat),
                    "lng": float(clng),
                    "boundary": boundary,
                })
            lng += cell_edge_deg
        lat += cell_edge_deg

    log.info("Generated %d candidate hexes for bounds %s at resolution %d",
             len(out), bounds, resolution)
    return out
